export const categoriesData = [
  {
    name: "Non-Pharmaceuticals",
    description: "Essential supplies for various medical procedures and patient care.",
    subcategories: [
      {
        name: "Infusion & Injection",
        slug: "infusion-injection",
        image: "/assets/images/infusion/infusion.jpg",
        products: [
          { name: "Infusion Set", image: "/assets/images/infusion/Infusion Set.jpeg" },
          { name: "Blood Transfusion Set", image: "/assets/images/infusion/Blood Transfusion Set.jpeg" },
          { name: "Needle", image: "/assets/images/infusion/Needle.jpg" },
          { name: "Syringe", image: "/assets/images/infusion/Syringe.jpg" },
          { name: "Scalp Vein Set", image: "/assets/images/infusion/Scalp Vein Set.png" },
          { name: "IV Cannula", image: "/assets/images/infusion/IV Cannula.jpeg" },
          { name: "Blood Collection Needle", image: "/assets/images/infusion/infusion.jpg" },
          { name: "Blood Collection Tube", image: "/assets/images/infusion/Blood Collection Tube.png" },
        ],
      },
      {
        name: "Urology",
        slug: "urology",
        image: "/assets/images/urology/urology.jpg",
        products: [
          { name: "Latex Foley Catheter", image: "/assets/images/urology/Latex Foley Catheter.jpg" },
          { name: "Silicone Foley Catheter", image: "/assets/images/urology/Silicone Foley Catheter.jpeg" },
          { name: "PVC Nelaton Catheter", image: "/assets/images/urology/PVC Nelaton Catheter.jpg" },
          { name: "Urine Bag", image: "/assets/images/urology/Urine Bag.jpeg" },
        ],
      },
      {
        name: "Anesthesia",
        slug: "anesthesia",
        image: "/assets/images/anaesthesia/anaesthesia.jpeg",
        products: [
          { name: "Endotracheal Tube", image: "/assets/images/anaesthesia/Endotracheal Tube.jpeg" },
          { name: "Tracheostomy Tube", image: "/assets/images/anaesthesia/Tracheostomy Tube.jpg" },
          { name: "Intubating Stylet", image: "/assets/images/anaesthesia/Intubating Stylet.jpg" },
          { name: "Oropharyngeal Airway", image: "/assets/images/anaesthesia/Oropharyngeal Airway.jpg" },
          { name: "Nasopharyngeal Airway", image: "/assets/images/anaesthesia/Nasopharyngeal Airway.jpg" },
          { name: "Laryngeal Mask Airway", image: "/assets/images/anaesthesia/Laryngeal Mask Airway.jpeg" },
          { name: "Air Cushion Mask", image: "/assets/images/anaesthesia/Air Cushion Mask.jpg" },
        ],
      },
      {
        name: "Respiratory",
        slug: "respiratory",
        image: "/assets/images/respiratory/respiratory.jpeg",
        products: [
          { name: "Oxygen Mask", image: "/assets/images/respiratory/Oxygen Mask.jpg" },
          { name: "Nebulizer Mask", image: "/assets/images/respiratory/Nebulizer Mask.jpeg" },
          { name: "Nasal Oxygen Cannula", image: "/assets/images/respiratory/Nasal Oxygen Cannula.jpg" },
        ],
      },
      {
        name: "Patient Care",
        slug: "patient-care",
        image: "/assets/images/patientcare/suction Catheter.jpeg",
        products: [
          { name: "Suction Catheter", image: "/assets/images/patientcare/Suction Catheter.jpg" },
          { name: "Feeding Tube", image: "/assets/images/patientcare/Feeding Tube.png" },
          { name: "Stomach Tube", image: "/assets/images/patientcare/Stomach Tube.png" },
          { name: "Ryle's Tube", image: "/assets/images/patientcare/Ryle's Tube.jpeg" },
          { name: "Yankauer Suction Set", image: "/assets/images/patientcare/Yankauer Suction Set.jpg" },
          { name: "Rectal Tube", image: "/assets/images/patientcare/Rectal Tube.png" },
          { name: "Face Mask", image: "/assets/images/patientcare/Face Mask.jpeg" },
          { name: "Vaginal Speculum", image: "/assets/images/patientcare/Vaginal Speculum.jpg" },
          { name: "Gloves", image: "/assets/images/patientcare/Gloves.jpeg" },
        ],
      },
    ],
  },
  {
    name: "Medical Equipment & Surgical Items",
    description: "Advanced equipment and instruments for diagnostics, surgery, and patient monitoring.",
    subcategories: [
      {
        name: "Patient Monitor",
        slug: "patient-monitor",
        image: "/assets/images/patientmonitor/Vital Sign Monitor.jpg",
        products: [
          { name: "Modular Monitor", image: "/assets/images/patientmonitor/Modular Monitor.jpg" },
          { name: "Compact Monitor", image: "/assets/images/patientmonitor/Compact Monitor.jpg" },
          { name: "Vital Sign Monitor", image: "/assets/images/patientmonitor/Vital Sign Monitor.jpg" },
        ],
      },
      {
        name: "Monitor/ECG/Defibrillator",
        slug: "monitor-ecg-defibrillator",
        image: "/assets/images/defibrillator/AED Defibrillator.jpeg",
        products: [
          { name: "Transport Monitor", image: "/assets/images/defibrillator/Transport Monitor.jpg" },
          { name: "3/6/12-Channel ECG", image: "/assets/images/defibrillator/Channel ECG.jpg" },
          { name: "ECG Holter", image: "/assets/images/defibrillator/ECG Holter.png" },
          { name: "PC ECG/Stress Test ECG", image: "/assets/images/defibrillator/Stress Test ECG.jpg" },
          { name: "AED Defibrillator", image: "/assets/images/defibrillator/AED Defibrillator.jpeg" },
          { name: "Defibrillator Monitor", image: "/assets/images/defibrillator/Defibrillator Monitor.jpeg" },
        ],
      },
      {
        name: "Pump/Video Laryngoscope/Diathermy Machine",
        slug: "pump-laryngoscope-diathermy",
        image: "/placeholder.svg",
        products: [
          { name: "Syringe Pump", image: "/placeholder.svg" },
          { name: "Infusion Pump", image: "/placeholder.svg" },
          { name: "Feeding Pump", image: "/placeholder.svg" },
          { name: "Vein Finder", image: "/placeholder.svg" },
          { name: "Diathermy Machine", image: "/placeholder.svg" },
          { name: "Video Laryngoscope", image: "/placeholder.svg" },
        ],
      },
      {
        name: "Anesthesia/Ventilator/CPAP",
        slug: "anesthesia-ventilator-cpap",
        image: "/placeholder.svg",
        products: [
          { name: "Anesthesia Machine", image: "/placeholder.svg" },
          { name: "Ventilator Machine", image: "/placeholder.svg" },
          { name: "Neonatal Ventilator", image: "/placeholder.svg" },
          { name: "Transport/Emergency Ventilator", image: "/placeholder.svg" },
          { name: "CPAP/APAP/BIPAP", image: "/placeholder.svg" },
        ],
      },
      {
        name: "Operating Light",
        slug: "operating-light",
        image: "/placeholder.svg",
        products: [
          { name: "LED Operating Light", image: "/placeholder.svg" },
          { name: "Shadowless Operating Light", image: "/placeholder.svg" },
          { name: "Examination Light", image: "/placeholder.svg" },
        ],
      },
      {
        name: "Operating Table/Suction Machine",
        slug: "operating-table-suction",
        image: "/placeholder.svg",
        products: [
          { name: "Electric Operating Table", image: "/placeholder.svg" },
          { name: "Mechanical Operating Table", image: "/placeholder.svg" },
          { name: "Obstetric Table", image: "/placeholder.svg" },
          { name: "Suction Machine", image: "/placeholder.svg" },
        ],
      },
      {
        name: "Maternal & Neonatal Healthcare",
        slug: "maternal-neonatal-healthcare",
        image: "/placeholder.svg",
        products: [
          { name: "Infant Incubator", image: "/placeholder.svg" },
          { name: "Transport Incubator", image: "/placeholder.svg" },
          { name: "Infant Radiant Warmer", image: "/placeholder.svg" },
          { name: "Bilirubin Phototherapy Unit", image: "/placeholder.svg" },
          { name: "Video Colposcope", image: "/placeholder.svg" },
          { name: "Fetal & Maternal Monitor", image: "/placeholder.svg" },
        ],
      },
      {
        name: "Hospital Bed",
        slug: "hospital-bed",
        image: "/placeholder.svg",
        products: [
          { name: "Hospital Bed", image: "/placeholder.svg" },
          { name: "Children Bed", image: "/placeholder.svg" },
          { name: "Mattress", image: "/placeholder.svg" },
          { name: "Hospital Stretcher", image: "/placeholder.svg" },
          { name: "Stretcher/Examination Table", image: "/placeholder.svg" },
          { name: "Bedside/Overbed Table", image: "/placeholder.svg" },
          { name: "Medical Trolley", image: "/placeholder.svg" },
          { name: "ENT & Dental Unit", image: "/placeholder.svg" },
        ],
      },
    ],
  },
]
